# Generated by Django 3.2 on 2021-04-23 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20210423_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predict_gujcet',
            name='given_entrance',
        ),
    ]
