# Generated by Django 3.2 on 2021-04-23 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0004_auto_20210423_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predict_JEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twelve_board', models.CharField(max_length=10)),
                ('twelve_marks', models.FloatField()),
                ('JEE_marks', models.FloatField()),
                ('enter_category', models.CharField(max_length=10)),
                ('choose_field', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
